server:
  port: 8888
http:
  client:
    max-total: 10000
    default-max-per-route: 1000
    connection-timeout: 1000
    connection-request-timeout: 2000
    socket-timeout: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/his
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: aizai051023
social:
  insurance:
    url: http://192.168.1.228:17001/szywsl/
    hospital:
      code: HHK00
    area: 440300
    channel: 10